### ISSUE TITLE
Stable Release

### ISSUE THREAD

**Issue by cihantas** [maxim2266/FullFIX#1]
Hello Maxim,

First of all: _Thank you_ for your hard work.

I'm planning to use FullFIX for a mid-large research project and am therefore highly interested in getting this to stable status.

Are there any todos on your list regarding functionality (or anything else) of this library? How could the community be of help?

-- Tas

**Comment by maxim2266** [comment]
Thanks @cihantas . At the moment there is not much activity going on around this project. I believe it is reasonably stable, since no issues have been raised against it.
