### ISSUE TITLE
Do you expect this to work on Windows Subsystem for Linux?

### ISSUE THREAD

**Issue by harshhacks** [maxim2266/FullFIX#3]
I'm currently working on a project to parse log files full of FIX messages and create an orderbook from them. Most of my messages are of the form MarketDataFullRefresh and those are the ones I'm primarily concerned with. 

I tried to build and run this on Windows and as expected it didn't work out because the code uses some Linux primitives. I'm curious if this will work on WSL2, however, as most of my infra is Windows based and I want to be prepared if I need to migrate it all to Linux. 

Sidenote: I was able to build and run the FFP Repo in Windows but it doesn't have the functionality to build the parser tree from an XML spec. 

Thanks!

**Comment by maxim2266** [comment]
At the moment I don't have any Windows machine, so I cannot tell whether it works on WSL or not, but I suppose it should.

**Comment by harshhacks** [comment]
This worked on WSL, thanks!
